//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Organize
    {
        public string OrganizeId { get; set; }
        public Nullable<int> Category { get; set; }
        public string ParentId { get; set; }
        public string EnCode { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Nature { get; set; }
        public string OuterPhone { get; set; }
        public string InnerPhone { get; set; }
        public string Fax { get; set; }
        public string Postalcode { get; set; }
        public string Email { get; set; }
        public string ManagerId { get; set; }
        public string Manager { get; set; }
        public string ProvinceId { get; set; }
        public string CityId { get; set; }
        public string CountyId { get; set; }
        public string Address { get; set; }
        public string WebAddress { get; set; }
        public Nullable<System.DateTime> FoundedTime { get; set; }
        public string BusinessScope { get; set; }
        public Nullable<int> Layer { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
